[local]
localhost

[mongodb]
mongodb-dev.indurthi.online

[catalogue]
catalogue-dev.indurthi.online

[redis]
redis-dev.indurthi.online

[user]
user-dev.indurthi.online

[cart]
cart-dev.indurthi.online

[mysql]
mysql-dev.indurthi.online

[shipping]
shipping-dev.indurthi.online

[rabbitmq]
rabbitmq-dev.indurthi.online

[payment]
payment-dev.indurthi.online

[frontend]
frontend-dev.indurthi.online

